Repository GTBitsOfGood/gen-soln, pull requests merged in 2020-04, with the labels that each got.

#25 Create dynamic routes for non-profit donation
  components/Branding.tsx
  components/ButtonWithNonprofitColor.tsx
  components/auth/AuthPageLayout.tsx
  components/donation/DonationPageFormAmountStep.tsx
  components/donation/DonationPageFormBody.tsx
  components/donation/DonationPageFormHeader.tsx
  components/donation/DonationPageHeaderSelect.tsx
  components/donation/DonationPageLayout.tsx
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/donate/[id].tsx
  pages/index.ts
  pages/index.tsx
  public/21311_backgroundImage.png
  public/21311_logo.png
  public/46546_backgroundImage.jpeg
  public/46546_logo.jpg
  public/nonProfitBackgroundImage.png
  utils/DummyData.ts
  utils/theme.ts
  utils/types.ts
  utils/util.ts
  yarn.lock
Labels: merge_first

#17 Incorporate design feedback into UI
  components/Branding.tsx
  components/ButtonWithNonprofitColor.tsx
  components/auth/AuthPageForm.tsx
  components/auth/AuthPageLayout.tsx
  components/auth/LoginFormEmailField.tsx
  components/auth/LoginFormPasswordField.tsx
  components/auth/RecoverPasswordFormContent.tsx
  components/donation/DonationPageFormAmountStep.tsx
  components/donation/DonationPageFormBody.tsx
  components/donation/DonationPageFormHeader.tsx
  components/donation/DonationPageFormNavigation.tsx
  components/donation/DonationPageHeaderSelect.tsx
  components/donation/DonationPageLayout.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/donate/[id].tsx
  pages/index.ts
  pages/index.tsx
  public/21311_backgroundImage.png
  public/21311_logo.png
  public/46546_backgroundImage.jpeg
  public/46546_logo.jpg
  public/nonProfitBackgroundImage.png
  utils/DummyData.ts
  utils/theme.ts
  utils/types.ts
  utils/util.ts
  yarn.lock
Labels: merge_later

#33 State management for donation page (still using dummy data)
  components/donation/DonationPage.tsx
  components/donation/DonationPageFormAmountStep.tsx
  components/donation/DonationPageFormBody.tsx
  components/donation/DonationPageFormContactStep.tsx
  components/donation/DonationPageFormHeader.tsx
  components/donation/DonationPageFormNavigation.tsx
  components/donation/DonationPageHeader.tsx
  components/donation/DonationPageHeaderSelect.tsx
  components/donation/DonationPageLayout.tsx
  components/donation/reducer.ts
  components/donation/types.ts
  package.json
  pages/donate/[id].tsx
  utils/DummyData.ts
  utils/types.ts
  yarn.lock
Labels: merge_first

#32 Backend refactors and a couple of bug fixes
  components/auth/AuthPageForm.tsx
  components/auth/LoginFormContent.tsx
  components/auth/RecoverPasswordFormContent.tsx
  components/donation/DonationPage.tsx
  components/donation/DonationPageFormAmountStep.tsx
  components/donation/DonationPageFormBody.tsx
  components/donation/DonationPageFormContactStep.tsx
  components/donation/DonationPageFormHeader.tsx
  components/donation/DonationPageFormNavigation.tsx
  components/donation/DonationPageHeader.tsx
  components/donation/DonationPageHeaderSelect.tsx
  components/donation/DonationPageLayout.tsx
  components/donation/reducer.ts
  components/donation/types.ts
  config.ts
  package.json
  pages/api/checkToken.js
  pages/api/checkToken.ts
  pages/api/createDonation.js
  pages/api/createDonation.ts
  pages/api/createNonprofit.js
  pages/api/createNonprofit.ts
  pages/api/getNonprofitNames.js
  pages/api/getNonprofitNames.ts
  pages/api/login.js
  pages/api/login.ts
  pages/api/signup.js
  pages/api/signup.ts
  pages/donate/[id].tsx
  pages/index.ts
  server/actions/admin.js
  server/actions/donation.js
  server/actions/nonprofit.js
  tsconfig.json
  utils/DummyData.ts
  utils/types.ts
  utils/util.ts
  yarn.lock
Labels: merge_later

#35 Backend Stripe Additions + Others
  components/AdminLoginLink.tsx
  components/Branding.tsx
  components/auth/AuthPageLayout.tsx
  components/auth/LoginFormContent.tsx
  components/auth/RecoverPasswordFormContent.tsx
  components/donation/DonationPageFormHeader.tsx
  components/donation/DonationPageHeaderBranding.tsx
  components/donation/DonationPageHeaderSelect.tsx
  config.ts
  package.json
  pages/_document.tsx
  pages/api/paymentIntents.js
  public/74067685_logo.png
  public/88484076_background.png
  public/88484076_logo.png
  public/89360274_background.jpg
  public/89360274_logo.jpg
  public/backgrounds/64357724.png
  public/backgrounds/92232372.png
  public/bog-logo.svg
  public/favicon.png
  public/logos/46099993.png
  public/logos/64357724.png
  public/logos/92232372.png
  public/signin-illust.png
  public/site/bog-logo.svg
  public/site/favicon.png
  public/site/login.png
  yarn.lock
Labels: backend, dependencies

#37 MVP
  components/donation/DonationPage.tsx
  components/donation/DonationPageFormBody.tsx
  components/donation/DonationPageFormContactStep.tsx
  components/donation/DonationPageHeaderSelect.tsx
  components/donation/DonationPageThankYou.tsx
  components/donation/StripeInput.jsx
  components/donation/reducer.ts
  components/donation/useStripePayment.ts
  config.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/createDonation.ts
  pages/api/paymentIntents.js
  pages/api/paymentIntents.ts
  pages/donate/[id].tsx
  pages/index.ts
  requests/donation.ts
  server/actions/donation.js
  server/actions/donation.ts
  server/models/donation.js
  utils/types.ts
  utils/util.ts
  yarn.lock
Labels: merge_first

#36 Using Stripe Elements for last Donation Form
  components/AdminLoginLink.tsx
  components/auth/LoginFormContent.tsx
  components/donation/DonationPage.tsx
  components/donation/DonationPageFormBody.tsx
  components/donation/DonationPageFormContactStep.tsx
  components/donation/DonationPageFormNavigation.tsx
  components/donation/DonationPageFormPaymentStep.tsx
  components/donation/DonationPageHeaderBranding.tsx
  components/donation/DonationPageHeaderSelect.tsx
  components/donation/DonationPageThankYou.tsx
  components/donation/StripeInput.jsx
  components/donation/StripeTextField.tsx
  components/donation/reducer.ts
  components/donation/useStripePayment.ts
  config.ts
  next.config.js
  package.json
  pages/_app.tsx
  pages/api/createDonation.ts
  pages/api/paymentIntents.js
  pages/api/paymentIntents.ts
  pages/donate/[id].tsx
  pages/index.ts
  requests/donation.ts
  server/actions/donation.js
  server/actions/donation.ts
  server/models/donation.js
  utils/theme.ts
  utils/types.ts
  utils/util.ts
  yarn.lock
Labels: merge_later
