Repository GTBitsOfGood/gen-soln, pull requests merged in 2020-09, with the labels that each got.

#120 Creates EventsPageLayout component
  components/events/EventsPageLayout.tsx
Labels: VMS, frontend

#122 Creates root component for event page
  components/events/EventsPage.tsx
  pages/events/index.tsx
Labels: VMS, frontend

#125 Add getUpcomingEvents action
  server/actions/events.ts
  server/models/event.js
  utils/types.ts
Labels: VMS, backend

#133 Refactored stripe keys and updated all references of old fields
  config.ts
  pages/_app.tsx
  server/actions/donation.ts
Labels: DMS

#138 Add actions createStripeAccount() and linkStripeAccount()
  .env
  config.ts
  server/actions/donation.ts
  server/actions/nonprofit.ts
  server/index.js
  server/migration.ts
Labels: DMS, backend

#131 Add migration script for events
  server/migrations/20200913143420-seed-events.ts
  server/migrations/20200913210455-migrate-nonprofits-add-events.ts
Labels: VMS, backend

#145 [DMS] Adds migrations script for test connected stripe account
  server/migrations/20200915011144-migrate-nonprofits-update-redcross-stripe-account.ts
Labels: DMS

#146 Email text change and db field refactor
  components/auth/form/RecoverPasswordFormContent.tsx
  config.ts
  server/index.js
  server/migration.ts
Labels: CORE, backend, frontend

#132 added stripeAccount field to nonprofit collection
  server/actions/nonprofit.ts
  server/migrations/20200913194527-migrate-nonprofits-add-stripe-account.ts
  server/models/nonprofit.js
  utils/types.ts
Labels: DMS

#163 Add getEventById action
  server/actions/events.ts
  server/models/event.js
  server/models/nonprofit.js
  utils/errors.ts
Labels: VMS, backend

#167 Add getAllEventIds action
  server/actions/events.ts
Labels: VMS, backend

#183 Add page for the /event/[id] route
  .gitignore
  config.ts
  package.json
  pages/events/[id].tsx
  server/actions/events.ts
  server/models/event.js
  utils/types.ts
Labels: VMS, backend

#180 Create stripe object with nonprofit stripe account
  components/donation/DonationPage.tsx
  components/donation/DonationPageMainContent.tsx
  components/donation/form/DonationPageForm.tsx
  pages/_app.tsx
  pages/donate/[id].tsx
  server/actions/nonprofit.ts
  utils/types.ts
Labels: DMS

#205 Refactored autocomplete input into shared component
  components/LocationAutocompleteInput.tsx
  components/events/EventPageLocationFilter.tsx
Labels: refactor

#203 Add pagination to event location queries
  server/actions/events.ts
  utils/types.ts
Labels: VMS, backend

#207 Create cause filter for events page
  components/events/EventsPage.tsx
  components/events/EventsPageDropdownFilter.tsx
  components/events/EventsPageLayout.tsx
  components/events/EventsPageLeftRailComponent.tsx
  pages/events/index.tsx
Labels: VMS, frontend, refactor
